# Generated by Django 3.2 on 2021-05-30 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mybookings',
            name='mhotle',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.hotels'),
        ),
        migrations.AlterField(
            model_name='mybookings',
            name='mvehicle',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.vehicle'),
        ),
    ]
