# Generated by Django 3.2 on 2021-05-30 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210530_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='loaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.destinations'),
        ),
    ]
