# Generated by Django 3.2 on 2021-06-03 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_hotels_loaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='pimg1',
            field=models.ImageField(blank=True, null=True, upload_to='pkgimg/'),
        ),
        migrations.AddField(
            model_name='package',
            name='pimg2',
            field=models.ImageField(blank=True, null=True, upload_to='pkgimg/'),
        ),
    ]
