# Generated by Django 3.2 on 2021-06-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210603_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='mybookings',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
