# Generated by Django 3.2 on 2021-06-10 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20210610_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mybookings',
            name='todate',
        ),
    ]
